"""Remover Unique da coluna 'title'  na tabela 'posts'

Revision ID: 96b9e9b3dc0c
Revises: 70c4b7257826
Create Date: 2025-01-16 08:56:00.241716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b9e9b3dc0c'
down_revision: Union[str, None] = '70c4b7257826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('published', sa.BOOLEAN(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
