"""Add nullable=False na Coluna 'active' na tabela 'users'

Revision ID: d9d740cc1ece
Revises: 96b9e9b3dc0c
Create Date: 2025-01-20 11:05:48.725948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d740cc1ece'
down_revision: Union[str, None] = '96b9e9b3dc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('published', sa.BOOLEAN(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
